# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build Jar

on: [workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: |
        cd ../
        git clone https://github.com/resess/DynamicSlicingCore
        cd DynamicSlicingCore/core
        mvn -DskipTests -B package install --file pom.xml
        cd ../../Slicer4J/Slicer4J
        mvn -DskipTests -B package install --file pom.xml
        mkdir artifacts
        echo "PWD: $(pwd)"
    - name: find & copy jars
      run: |
        mkdir artifacts
        echo "PWD: $(pwd)"
        cp Slicer4J/target/slicer4j-jar-with-dependencies.jar artifacts/slicer4j-jar-with-dependencies.jar
    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: Slicer4J Jar
        path: artifacts
